language: node_js
node_js:
  - "node"
install:
  - npm install
before_script:
  - npm install now
script:
  - npm run lint
deploy:
  provider: script
  script:
  - npm deploy
  on:
    branch: feat/travis
  skip_cleanup: true
